export enum UserType {
  SUPER_ADMIN = 'SUPER_ADMIN',
  TENANT_ADMIN = 'TENANT_ADMIN',
  TENANT_ADMIN_ALT = 'TENANT_ADMINISTRATION',
  TENANT_USER = 'TENANT_USER',
  USER = 'USER',
}

export const USER_TYPE_HIERARCHY = {
  [UserType.SUPER_ADMIN]: 1,
  [UserType.TENANT_ADMIN]: 2,
  [UserType.TENANT_ADMIN_ALT]: 2,
  [UserType.TENANT_USER]: 3,
  [UserType.USER]: 3,
};